import Head from "next/head";
import { gql } from "@apollo/client";
import client from "../apollo-client";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Jobs from "../components/Jobs/Jobs";
export default function Home({ JobsInfo }) {
  return (
    <Head>
      <title>GraphQL Jobs App</title>
      <Navbar />
      <Hero />
      <Jobs JobsInfo={JobsInfo} />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query Response {
        jobs {
          id
          title
          company {
            name
          }
          cities {
            name
          }
          remotes {
            name
          }
          tags {
            name
          }
        }
      }
    `,
  });

  return {
    props: {
      JobsInfo: data.jobs,
    },
  };
}
